### ISSUE TITLE
[錯誤回報]

### ISSUE THREAD

**Issue by Anonymous-AAAA** [seriaati/shenhe_bot#283]
## 哪個指令出錯了？

The link of "功能列表" in `README.md` is invalid.

## 如果可行的話，請告訴我重現該錯誤的步驟

https://seriaati.github.io/shenhe_website/features.html

## 請貼上「除錯用訊息」

It shows 404 not found when visit.

## 如果方便的話，請留下你的 dc tag

[꧁AAAA꧂#2713](https://discord.com/users/755269122597585018)

**Comment by seriaati** [comment]
Thanks for reporting this, it is fixed now.
