### ISSUE TITLE
[Feature Request] Spiral abyss leaderboard like tavern bot

### ISSUE THREAD

**Issue by BommBloom** [seriaati/shenhe_bot#405]
Is it possible to add spiral abyss leaderboard features like in tavern bot? 
![abyss-leaderboard](https://user-images.githubusercontent.com/118669314/202903475-20bb77f4-f87b-4d65-96ba-3d3a0f5fbd07.png)

**Comment by seriaati** [comment]
sure, there was a plan for leaderboard rework but it kept getting pushed back because there were other features I want to make.

this feature will now be prioritized, I will try to implement this as soon as possible.

thank you for the suggestion.
