### ISSUE TITLE
[Feature Request] add current spiral abyss blessing abyssal moon on /abyss-enemies command

### ISSUE THREAD

**Issue by seriaati** [seriaati/shenhe_bot#493]
Find latest buff in: https://github.com/Dimbreath/GenshinData/blob/9903ecb00655ab9fbe8799ecd7f04ea72a6d3c44/ExcelBinOutput/TowerScheduleExcelConfigData.json#L3657

Find buff description in: https://github.com/Dimbreath/GenshinData/blob/9903ecb00655ab9fbe8799ecd7f04ea72a6d3c44/ExcelBinOutput/DungeonLevelEntityConfigData.json#L6162

**Comment by kravetsone** [comment]
hi, how do I get access to that repository?
