### ISSUE TITLE
[Bug Report] Cannot login hoyolab account by using firefox

### ISSUE THREAD

**Issue by momu54** [seriaati/shenhe_bot#501]
![圖片](https://user-images.githubusercontent.com/96234201/211012326-8af7bcf0-00f4-4e0f-9f9c-a7b73cf32259.png)

I tried Email and password login and cookie login
but it still not working

+ "Next" Button isn't clickable.

**Comment by GauravM512** [comment]
use chromium based browser

**Comment by seriaati** [comment]
Firefox is not supported, please use a chromium based browser, like Google Chrome or Microsoft Edge

**Comment by GauravM512** [comment]
> ![圖片](https://user-images.githubusercontent.com/96234201/211012326-8af7bcf0-00f4-4e0f-9f9c-a7b73cf32259.png)
> 
> I tried Email and password login and cookie login but it still not working
> 
> * "Next" Button isn't clickable.

Firefox support is added! Enjoy
