### ISSUE TITLE
[Feature Request] auto redeem code

### ISSUE THREAD

**Issue by seriaati** [seriaati/shenhe_bot#523]

**Comment by GauravM512** [comment]
This has issued 
1) `cookie_token` expires for some users
2) `cookie_token` can only be reloaded for users signed up using email method in hu tao login
3) if it is a turn on feature, you'll have to either force user to use email method in hu tao login or tell them to re-enter new cookies within an interval

**Comment by seriaati** [comment]
it will be disabled by default

**Comment by seriaati** [comment]
Added in https://github.com/seriaati/shenhe_bot/commit/8f6ac98ba364b74a367ba16846c837ae487f4029
