### ISSUE TITLE
[錯誤回報] 沒辦法找圖

### ISSUE THREAD

**Issue by YueMu1022** [seriaati/shenhe_bot#65]
## 哪個指令出錯了？
`/waifu waifu`

## 如果可行的話，請告訴我重現該錯誤的步驟
在私訊中使用`/waifu waifu` 選擇~~多情模式~~

## 請貼上「除錯用訊息」
![image](https://user-images.githubusercontent.com/96234201/180895370-9412ed24-73d5-4217-a309-6f61e4f73a1c.png)

## 如果方便的話，請留下你的 dc tag
某幕#1501

**Comment by seriaati** [comment]
請問是在私訊中使用嗎

**Comment by seriaati** [comment]
https://github.com/seriaati/shenhe_bot/commit/98c3d1ca0317a2505e3ad212404d0def6a1d40b7

**Comment by YueMu1022** [comment]
笑死直接guild only
