### ISSUE TITLE
[錯誤回報]

### ISSUE THREAD

**Issue by actcfx** [seriaati/shenhe_bot#67]
## 哪個指令出錯了？
/register

## 如果可行的話，請告訴我重現該錯誤的步驟
提交cookie之後一定出現

## 請貼上「除錯用訊息」
Traceback (most recent call last):
  File "C:\Users\alice\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\modal.py", line 187, in _scheduled_task
    await self.on_submit(interaction)
  File "C:\Users\alice\shenhe_public\cogs\genshin.py", line 59, in on_submit
    result, success = await self.genshin_app.setCookie(i.user.id, self.cookie.value, i.locale)
  File "C:\Users\alice\shenhe_public\utility\apps\GenshinApp.py", line 31, in setCookie
    client.lang = user_locale or locale
  File "C:\Users\alice\AppData\Local\Programs\Python\Python310\lib\site-packages\genshin\client\components\base.py", line 96, in lang
    raise ValueError(f"{lang} is not a valid language, must be one of: " + ", ".join(constants.LANGS))
ValueError: zh-TW is not a valid language, must be one of: zh-cn, zh-tw, de-de, en-us, es-es, fr-fr, id-id, ja-jp, ko-kr, pt-pt, ru-ru, th-th, vi-vn

## 如果方便的話，請留下你的 dc tag
北極狐#9914

**Comment by actcfx** [comment]
補充一下，這是cookie
mi18nLang=zh-tw; _MHYUUID=edca0ec6-4cbb-49c3-ad4c-6a76c314b9ea; G_ENABLED_IDPS=google; _ga_54PBK3QDF4=GS1.1.1651209175.1.1.1651209260.0; _ga_9TTX3TE5YL=GS1.1.1655299409.1.0.1655299409.0; _ga=GA1.2.925284012.1643564312; _gid=GA1.2.1821272934.1658847798; DEVICEFP_SEED_ID=1844308268a3adf1; DEVICEFP_SEED_TIME=1658847797980; DEVICEFP=38d7ea5e39dac; ltoken=zpOFvy3ihmDNWJLNKKT13Mhfm37mjr2TRoiBnIu2; ltuid=182600697; cookie_token=Mn4jOxMZQimX7aMGpS4ZLsoPzsc1Et70sIwuS5sE; account_id=182600697; _gat=1

**Comment by actcfx** [comment]
補充一下，這是cookie
mi18nLang=zh-tw; _MHYUUID=edca0ec6-4cbb-49c3-ad4c-6a76c314b9ea; G_ENABLED_IDPS=google; _ga_54PBK3QDF4=GS1.1.1651209175.1.1.1651209260.0; _ga_9TTX3TE5YL=GS1.1.1655299409.1.0.1655299409.0; _ga=GA1.2.925284012.1643564312; _gid=GA1.2.1821272934.1658847798; DEVICEFP_SEED_ID=1844308268a3adf1; DEVICEFP_SEED_TIME=1658847797980; DEVICEFP=38d7ea5e39dac; ltoken=zpOFvy3ihmDNWJLNKKT13Mhfm37mjr2TRoiBnIu2; ltuid=182600697; cookie_token=Mn4jOxMZQimX7aMGpS4ZLsoPzsc1Et70sIwuS5sE; account_id=182600697; _gat=1

**Comment by seriaati** [comment]
cookie 不建議放在公開的地方哦
