### ISSUE TITLE
[功能請求] 將常用指令添加到訊息右鍵列表

### ISSUE THREAD

**Issue by YueMu1022** [seriaati/shenhe_bot#69]
## 請描述你的想法
~~每次都要打/acc之類的好麻煩~~
還要切去指令台

**Comment by Ayaakaa** [comment]
就你很懶呀

**Comment by YueMu1022** [comment]
~~我覺得某雪很大機率不做~~
他連私訊的bug都不修
直接設guild only

**Comment by seriaati** [comment]
要哪些指令

**Comment by YueMu1022** [comment]
能加的全加了
![:ayaka_heh:](https://cdn.discordapp.com/emojis/989409024518787072.webp?size=96&quality=lossless)
