### ISSUE TITLE
[功能請求]

### ISSUE THREAD

**Issue by YueMu1022** [seriaati/shenhe_bot#71]
## 請描述你的想法
把右鍵快捷指令也加到訊息右鍵裡面

![:ayaka_heh:](https://cdn.discordapp.com/emojis/989409024518787072.webp?size=96&quality=lossless)

**Comment by Ayaakaa** [comment]
我認為沒什麼需要，如果新增太多東西到訊息右鍵菜單，語錄效率會大幅受到影響呀

**Comment by YueMu1022** [comment]
hmm好吧
~~可是語錄有那麼追求效率嗎~~

**Comment by seriaati** [comment]
按頭像就好了
